main: com.kale_ko.deathswap.Main
name: DeathSwap
version: 1.0.0
author: Kale Ko

api-version: 1.16

commands:
    Deathswap:
        description: All the deathswap commands
        usage: /deathswap (help, start, stop, reload)